config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'
  resources :orders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :items, dependent: :destroy
  accepts_nested_attributes_for :items, allow_destroy: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  def index
    @orders = Order.order(created_at: :desc)
  end

  def show; end

  def new
    @order = Order.new
    @order.items.build
  end

  def edit; end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: 'Order was successfully created.' }
        format.js
      else
        format.js
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: 'Order was successfully updated.' }
        format.js
      else
        format.js
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.js
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:name, items_attributes: %i[id name quantity _destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JqueryProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_error.html.erb
 <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/orders/_form.html.erb
<div style=" display: flex; justify-content: center; background-color:  #f0f2f5">
  <div style="background-color:  white; padding: 50px; margin: 30px; border-radius: 10px; ">
    <%= form_with(model: order , local: false ) do |form| %>        
      <h2 style="text-align: center"  >
        <% if order.id.present? %>
          Edit 
        <% else %>
          Create
        <% end %>
          Product 
       </h2>
        <div class="modal-body">

          <div id="errorarea">
          </div>

          <div class="csform" >
            <%= form.label :Name %>
          </div>
          <div>
            <%= form.text_field :name %>
          </div>
          <br>
          </div>
            <div id="items">
            <%= form.fields_for :items do |item_form| %>
            <%= render 'item_fields', f: item_form %>
            <% end %>
          </div>
          <div style="text-align: right;" ,class="links" >
            <%= link_to_add_association 'Add item', form, :items, class: 'btn btn-primary' %>
          </div>         
          <br>
            <div class="modal-footer">
              <button type="button" class="btn btn-light close-modal" data-bs-dismiss="modal">Close</button>
            <%= form.submit  class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>

 

app/views/orders/_item_fields.html.erb
<div class="nested-fields">
  <%= link_to_remove_association 'Remove item', f, class: 'btn btn-danger' %>
  <div class="form_design" >
    <%= f.label :Item_Name %>
      <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form_design" >
    <%= f.label :Quantity %>
     <%= f.number_field :quantity, class: 'form-control' %>
  </div>
</div>

app/views/orders/_show.html.erb
<html>
    <head>
        <title>Show Page</title>
    </head>

    <body>
        <div class='container' >
            <div class="modal-body" >
                <p>
                    <strong> Order Name:</strong>
                    <%= @order.name %>
                </p>
                    <% if @order.items.present? %>
                        <table class="table table-striped" >
                        <thead>
                        <th>Item Name</th>
                        <th>Quantity</th>
                        </thead>
                        <tbody>
                        <% @order.items.each do |oitem| %>
                            <tr>
                            <td><%= oitem.name %></td>
                            <td><%= oitem.quantity %></td>
                            </tr>
                        <% end %>
                        </tbody>
                    </table>
                    <% end %>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Close</button>
            </div>
        </div>

    </body>

</html>

app/views/orders/_user_row.html.erb
<tr id="userRow_<%= order.id %>" >
    <td><%= order.name %></td>
    <td><%= link_to 'Show', order , data: { bs_toggle: 'modal', bs_target: '#showordermodal', remote: true },class: "btn btn-info" %></td>
    <td><%= link_to 'Edit', edit_order_path(order) , data: { bs_toggle: 'modal', bs_target: '#editordermodal', remote: true } ,class: "btn btn-warning" %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "btn btn-danger"  %></td>
</tr>   

app/views/orders/create.js.erb
<% if @order.errors.any?  %>
     $("#errorarea").html("<%= escape_javascript render( 'error' , order: @order) %>");
<% else %>
    $("#userTable").prepend("<%= escape_javascript render( 'user_row' , order: @order) %>");
    $(".close-modal").click();
<% end %> 

app/views/orders/destroy.js.erb
$("#userRow_<%= @order.id %>").remove();

app/views/orders/edit.js.erb
$("#edituserform").html("<%= escape_javascript render( 'form' , order: @order) %>");

app/views/orders/index.html.erb
<html>
  <head>
    <title>Index Page</title>
  </head>

  <body>
    <div class='container' >
      <p id="notice"><%= notice %></p>

      <h1>Orders</h1>

      <table class="table table-hover" >
        <thead>
          <tr>
            <th>Order Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody id="userTable" >
          <% @orders.each do |order| %>
            <%= render 'user_row' , order: order %>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Order', new_order_path , data: { bs_toggle: 'modal', bs_target: '#newordermodal', remote: true }, class: "btn btn-success" %>

      <!-- Create Order Modal -->
      <div class="modal fade" id="newordermodal" tabindex="-1" aria-labelledby="newordermodalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="newordermodalLabel"> Create Order </h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="newuserform" >
            </div>
          </div>
        </div>
      </div>


      <!-- Edit User Modal -->
      <div class="modal fade" id="editordermodal" tabindex="-1" aria-labelledby="editordermodalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="editordermodalLabel"> Edit Order </h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="edituserform" >
            </div>
          </div>
        </div>
      </div>

      <!-- Edit User Modal -->
      <div class="modal fade" id="showordermodal" tabindex="-1" aria-labelledby="showordermodalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="showordermodalLabel"> Order Details </h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="showorderdetails" >
            </div>
          </div>
        </div>
      </div>
    </div>  

#edited from github

  </body>

</html>

app/views/orders/new.js.erb
$("#newuserform").html("<%= escape_javascript render( 'form' , order: @order) %>");

app/views/orders/show.js.erb
$("#showorderdetails").html("<%= escape_javascript render( 'show' , order: @order) %>");

app/views/orders/update.js.erb
<% if @order.errors.any?  %>
    $("#errorarea").html("<%= escape_javascript render( 'error' , order: @order) %>");
<% else %>
    $("#userRow_<%= @order.id %>").replaceWith("<%= escape_javascript render( 'user_row' , order: @order) %>");
    $(".close-modal").click();
<% end %> 